## This file takes honduras, salvador and guatemala databasess and combine them into one 


```{r}
library(dplyr)
library(tidyr)     
library(readr)  
honduras<- read_csv("~/Desktop/UchicagoPolicyLab-Migration/Data/Honduras/Processed/municipality_summary.csv")
salvador <- read_csv("~/Desktop/UchicagoPolicyLab-Migration/Data/El Salvador/Processed/municipality_summary.csv")
```

```{r}
honduras <- honduras %>%
  mutate(
    Country = "Honduras",
    ISO3    = "HND"
  )

salvador <- salvador %>%
  mutate(
    Country = "El Salvador",
    ISO3    = "SLV"
  )
```
#Columns that exist in Honduras but NOT in El Salvador

```{r}
setdiff(names(honduras), names(salvador))

```
#Columns that exist in El Salvador but NOT in Honduras
```{r}
setdiff(names(salvador), names(honduras))
```

```{r}
combined_muni <- bind_rows(honduras, salvador)
common_cols <- intersect(names(honduras), names(salvador))

combined_muni  <- combined_muni  %>% select(all_of(common_cols))
combined_muni
```
```{r}
write_csv(combined_muni,
          "../Data/department_data.csv")
```


```{r}
honduras_emigrants<- read_csv("~/Desktop/UchicagoPolicyLab-Migration/Data/Honduras/Processed/emigration_summary.csv")
salvador_emigrants <- read_csv("~/Desktop/UchicagoPolicyLab-Migration/Data/El Salvador/Processed/emigration_summary.csv")
```

```{r}
honduras_emigrants <- honduras_emigrants %>%
  mutate(
    Country = "Honduras",
    ISO3    = "HND"
  )

salvador_emigrants <- salvador_emigrants %>%
  mutate(
    Country = "El Salvador",
    ISO3    = "SLV"
  )
```

```{r}
honduras_emigrants
```

```{r}
salvador_emigrants
```



#Columns that exist in Honduras but NOT in El Salvador

```{r}
setdiff(names(honduras_emigrants), names(salvador_emigrants))

```
#Columns that exist in El Salvador but NOT in Honduras
```{r}
setdiff(names(salvador_emigrants), names(honduras_emigrants))
```
```{r}
honduras_emigrants <- honduras_emigrants %>%
  mutate(
    depto = as.character(depto),
    munic = as.character(munic)
  )

salvador_emigrants <- salvador_emigrants %>%
  mutate(
    depto = as.character(depto),
    munic = as.character(munic)
  )
```

```{r}
combined_muni_em <- bind_rows(honduras_emigrants, salvador_emigrants)
common_cols_em <- intersect(names(honduras_emigrants), names(salvador_emigrants))

combined_muni_em <- combined_muni_em %>% select(all_of(common_cols_em))
combined_muni_em
```

```{r}
write_csv(combined_muni_em,
          "../Data/emigration_data.csv")
```
